{{- if not .Values.backend.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "devops-kb.backend.secretName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "devops-kb.backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.backend.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
